// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("FsBlogLib")>]
[<assembly: AssemblyProductAttribute("FsBlogLib")>]
[<assembly: AssemblyDescriptionAttribute("Blog aware, static site generation using F#.")>]
[<assembly: AssemblyVersionAttribute("0.4.1")>]
[<assembly: AssemblyFileVersionAttribute("0.4.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "FsBlogLib"
    let [<Literal>] AssemblyProduct = "FsBlogLib"
    let [<Literal>] AssemblyDescription = "Blog aware, static site generation using F#."
    let [<Literal>] AssemblyVersion = "0.4.1"
    let [<Literal>] AssemblyFileVersion = "0.4.1"
