#!/bin/bash

#getting latest FAKE via NuGet
if [ ! -f packages/FAKE/tools/FAKE.exe ]; then
        mono .nuget/nuget.exe install FAKE -OutputDirectory packages -ExcludeVersion -Prerelease
fi

mono packages/FAKE/tools/FAKE.exe build.fsx $@