#!/bin/bash

#getting latest FAKE via NuGet
if [ ! -f tools/FAKE/tools/FAKE.exe ]; then
        mono .nuget/nuget.exe install FAKE -OutputDirectory tools -ExcludeVersion -Prerelease
fi

mono tools/FAKE/tools/FAKE.exe fsblog.fsx $@